[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"