[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install && npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3002"
FRONTEND_URL = "https://todo-study-frontend.vercel.app"