[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "4173"

[environments.production.variables]
VITE_SUPABASE_URL = "${{VITE_SUPABASE_URL}}"
VITE_SUPABASE_ANON_KEY = "${{VITE_SUPABASE_ANON_KEY}}"

[environments.staging.variables]
VITE_SUPABASE_URL = "${{VITE_SUPABASE_URL_STAGING}}"
VITE_SUPABASE_ANON_KEY = "${{VITE_SUPABASE_ANON_KEY_STAGING}}"